Made ec2 instance public_ip optional
bitovi/github-actions-deploy-docker-to-ec2 pull request #18
Opened 2022-11-30 18:13 UTC by LeoDiazL

As we have the ELB DNS exposed, no common use for the EC2 instance to have a public IP

2022-12-01 12:38 UTC, mickmcgrath13 requested changes
one small docs change. otherwise, looks great!

2022-12-01 12:44 UTC, mickmcgrath13 commented
@LeoDiazL 2 things:
1. This pr is dependent on the domain one: https://github.com/bitovi/github-actions-deploy-docker-to-ec2/pull/9 (which should be good to merge and release, btw)
2. Should we update the output to reflect the LB url instead of the instance url? https://github.com/bitovi/github-actions-deploy-docker-to-ec2/blob/add-public-dns-config/operations/deployment/terraform/main.tf#L31-L35

2022-12-01 19:34 UTC, LeoDiazL commented on README.md
> +| `ec2_instance_public_ip` | T/F | Adds a public IP to the EC2 instance. Defaults to `false`. (App is exposed through an ELB) |
Then evey T/F should be adjusted to boolean

2022-12-01 19:36 UTC, LeoDiazL commented on operations/deployment/terraform/main.tf
>  }
Not sure this will work

2022-12-06 13:24 UTC, mickmcgrath13 commented
needs merge with main to resolve conflicts

2022-12-06 19:45 UTC, merged